### ISSUE TITLE
[crypto-conditions] Add this unit test to threshold cost test

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#10]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Saturday Oct 21, 2017 at 15:28 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/78_

----

```
 For example, if a threshold crypto-condition contains 5 sub-
   conditions with costs of 64, 64, 82, 84 and 84 and has a threshold of
   3, the cost is equal to the sum of the largest three sub-condition
   costs (82 + 84 + 84 = 250) plus 1024 times the number of sub-
   conditions (1024 * 5 = 5120): 5370
```

**Comment by pascalav** [comment]
A pull request is available: https://github.com/hyperledger/quilt/pull/70

Warning: 2 unit tests got added. One as described in this ticket, and one to assert that the number of sub-conditions is greater or equal to the threshold.

That second test will fail. It expects an IllegalArgumentException in that situation, and the current source throws an IndexOutOfBoundsException there. If desirable, source is fixed to match that test, at:
https://github.com/hyperledger/quilt/issues/71

**Comment by sappenin** [comment]
This is complete.
