### ISSUE TITLE
In this library, what is the "best" default encoding for Fulfillment.getEncodedPreimage and other byte-array data?

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#100]
@adrianhopebailie @earizon @michielbdejong 

This issue arises from the[discussion](https://github.com/hyperledger/quilt/pull/89#discussion_r165421147) in #89.

Currently, `Fulfillment.getEncodedPreimage` produces output in [Base64Url](https://en.wikipedia.org/wiki/Base64) encoding. However, in [ILP-over-HTTP](https://github.com/interledger/rfcs/blob/ilp-over-http/0000-ilp-over-http.md), the encoding is specified as being Base64.

If we leave things alone, then anyone using the ILP-Testnet's `ILP-over-HTTP` functionality will have to re-encode from Base64Url to Base64 in order to pass fulfillment data.

Thus, we have (at least) three choices here:

1. Do nothing. Have any code that needs to interface with both `ilp-over-http` and this `crypto-conditions` library just do the double-conversion. This may not be a bad choice because 1.) ilp-over-http is deprecated in favor of ILPv4-over-http, and 2) There's a case to be made that this encoding _should_ be Base64Url, so that anyone putting this data into a URL won't have to double-encode it.
1. Change the TestNet code to use Base64Url. I will defer to @michielbdejong on this, but I think this is a non-starter because the testnet has certain deprecation guarantees that would make this impractical.
1. Change this library to use `Base64` encoding in all places. Overall, this is not a bad choice, but would force anyone putting crypto-condition primitives into URLs to possibly have to re-encode them. This is probably more likely than any of the use-cases from 1 or 2 above.

I would be curious to hear pros/cons for picking either Base64 vs. Base64Url as a general choice. Thoughts anyone?

**Comment by earizon** [comment]
Maybe that can be selected in a Fulfillment builder parameter. By now default to Base64, and change to Base64Url once the testnet is updated. If Base64 is finally deprecated in favor of Base64Url then just drop/deprecate/ignore the builder setting.

**Comment by sappenin** [comment]
Closing this since CryptoConditions have moved to https://github.com/ripple/crypto-conditions, and for [ILP-over-HTTP](https://github.com/interledger/rfcs/blob/de237e8b9250d83d5e9d9dec58e7aca88c887b57/0000-ilp-over-http.md) the suggested crypto-condition should be the hashlock packaged in Quilt.
