### ISSUE TITLE
[crypto-conditions] Re-think Threshold Condition/Fulfillment Constructors per 

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#11]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Saturday Oct 21, 2017 at 15:42 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/79_

----

We need to re-think the Threshold Condition/Fulfillment Constructors per https://github.com/bigchaindb/cryptoconditions/issues/94.

Once that's done, I think we can better reason about #80.

**Comment by sappenin** [comment]
This is fixed.
