### ISSUE TITLE
Make InterledgerRejectPacket.getData return empty array by default.

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#119]
The default value of the immutable should be an empty byte array so developers constructing a new InterledgerRejectPacket don't have to specify the data field.

```
InterledgerRejectPacket.builder()
              .code(InterledgerErrorCode.F02_UNREACHABLE)
              .message("No Route to Destination!")
              .triggeredBy(...)
              .data(new byte[]{})
              .build()
```

can become this:

```java
InterledgerRejectPacket.builder()
              .code(InterledgerErrorCode.F02_UNREACHABLE)
              .message("No Route to Destination!")
              .triggeredBy(...)
              .build()
```

**Comment by pascalav** [comment]
Does the same holds for the 2 other packet types of ILP v4 (`InterledgerPreparePacket` and `InterledgerFulfillPacket`)?

I looked in the RFC (https://github.com/interledger/rfcs/blob/master/0027-interledger-protocol-4/0027-interledger-protocol-4.md) for an hint stating that the `data` field is optional, but I did not spot such a statement. But it indeed seems that it can be empty (i.e. zero-length).

I've a local branch for this issue and will adapt the commit accordingly (i.e. only enhancing `InterledgerRejectPacket` or all-3).

**Comment by sappenin** [comment]
Hey great question - the `data` field is _not_ optional, it must always be there. However, it can be empty, which should be the default setting.

Should look like this in the `AbstractInterledgerRejectPacket`:

```
   @Override
   @Default
   public byte[] getData(){
     return new byte[0];
   }
```

**Comment by pascalav** [comment]
Hi @sappenin, allright, the PR contains that default empty-value for the `data` field of all-3 packet type classes.
