### ISSUE TITLE
[ilp-core] Add LICENSE and CONTRIBUTOR agreement files

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#12]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Thursday Aug 18, 2016 at 10:44 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/7_

----

We should be using Apache 2.0 and have a license file and a contributor agreement file

**Comment by adrianhopebailie** [comment]
Closed in favour of #61
