### ISSUE TITLE
Error in InterledgerAddress Regex

### ISSUE THREAD

**Issue by adrianhopebailie** [hyperledger/quilt#128]
The DESTINATION_ADDRESS regex appears to be too restrictive:
 `(?=^.{1,1023}$)^(g|private|example|peer|self|test[1-3]?)[.]([a-zA-Z0-9_~-]+[.])+[a-zA-Z0-9_~-]+$` 

This forces the address to have at least 2 segments after the scheme which means a valid address like `peer.config` is considered invalid.

I believe this would be sufficient:
 `(?=^.{1,1023}$)^(g|private|example|peer|self|test[1-3]?)([.][a-zA-Z0-9_~-]+)+$`

**Comment by adrianhopebailie** [comment]
On hold pending the outcome of https://github.com/interledger/rfcs/issues/410

**Comment by adrianhopebailie** [comment]
Should be resolved as part of: #139

**Comment by sappenin** [comment]
Closing in favor of #139
