### ISSUE TITLE
[ilp-core] Update README

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#13]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Wednesday Aug 24, 2016 at 08:04 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/9_

----

- Project details
- Build instructions
- Contributor instructions

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/mrmx"><img src="https://avatars2.githubusercontent.com/u/86406?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mrmx](https://github.com/mrmx)**
_Thursday Aug 25, 2016 at 11:41 GMT_

----

I've prepared a global readme at https://github.com/everis-innolab/java-ilp-master that could serve as a blueprint.

**Comment by sappenin** [comment]
This is complete. Please open individual PRs or issues for discrete changes to the README moving forward.
