### ISSUE TITLE
AsnUintCodec can not accept zero.

### ISSUE THREAD

**Issue by dora-gt** [hyperledger/quilt#133]
https://github.com/hyperledger/quilt/blob/b0497ff75136a16e32a0336950c88d36e590e39e/codec-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUintCodec.java#L24

Isn't it `if (value.compareTo(BigInteger.ZERO) < 0) {` ?

This can not accept `0`.

**Comment by adrianhopebailie** [comment]
> Isn't it `if (value.compareTo(BigInteger.ZERO) < 0) {` ?

At first glance I think you are correct. Need to add some units tests for this case.

**Comment by dora-gt** [comment]
If you need, may I help creating test vectors? or do you have any plan to do it?

Though I'm not a specialist of QA, I think we need...

- Max, min test
- Edge case test
- Serialization/deserialization test

In addition, the tests have to be ran on different architecture like POWER-ish CPUs, Intel CPUs because of endian problem if we want to ensure that our code can work with the both endian.

**Comment by adrianhopebailie** [comment]
If you are able to do it that would be great!

I would recommend we have some files that contain JSON definitions like:

```
{
  "packetType" : "InterledgerPrepare",
  "amount" : "123",
...
  "oerEncoding" : "a8u23g87tre" //Base64 encoded
}

```

The the tests can load each file, parse the JSON, get the binary encoding and then decode that and compare the properties with the other values in the JSON. WDYT?

We should store these in the **interledger/rfcs** repo I think

@michielbdejong has a script that he suggested in the past that could be used to generate these test vectors

**Comment by dora-gt** [comment]
I thought just like it, and we should store the data in rfcs repo with the specification that Stefan  wrote before (https://github.com/interledger/rfcs/blob/docs/st-oer/0000-notes-on-oer-encoding/0000-notes-on-oer-encoding.md). *I want him to finish this and it to be merged haha*

However, I have 3 points, just wondering.

1. Don't we need more primitive test cases?
    - like `Uint8` or `Uint32` that Interledger OER supports
2. Considering the above, I propose a JSON format like this:
    - ``` { "asn1Type" : "Uint8", "value" : "123", "oerEncoding" : "xxxx" } ```
    - `value` may be hash, when it is a compound type like `InterledgerPacket`.
3. The methodology is a bit difficult because if we use some code that generate test cases, we have to write tests for it too. Shouldn't we write it on our own? or should we use a generator?
