### ISSUE TITLE
[ilp-core] Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#14]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Wednesday Apr 12, 2017 at 17:32 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/25_

----

As discussed on the Java ILP community call, we need to make it easier for new developers to checkout, build, and use Java ILP code.

To that end, we should be releasing versions of each library (java-ilp-core, crypto-conditions, etc) and pushing those to [Maven Central](https://search.maven.org/#search).

1. Create account at Sonatype for the organization org.interledger (this will allow us to create any modules under that).
1. Configure CircleCI to deploy artifacts to maven central.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Sunday May 21, 2017 at 20:42 GMT_

----

Step1 is to create an account with OSSRH.  I have started this process ([JIRA task here](https://issues.sonatype.org/browse/OSSRH-31442)), but this takes about 2 business days.  Once established, we'll be able to deploy artifacts to maven-central via OSSRH.

In the meantime, see this [PR](https://github.com/interledger/java-ilp-core/pull/43/files) that lays the groundwork for java-ilp-core.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Thursday Jul 20, 2017 at 14:49 GMT_

----

SNAPSHOT is published to sonatype. Once we have the library in a stable place for an initial release, we can push a 0.5.x release.

**Comment by sappenin** [comment]
@adrianhopebailie When you have more details from Hyperledger on the process for publishing artifacts, can you report that info back here?

Mentioning @ryjones as well.

**Comment by ryjones** [comment]
@jwagantall do we have documentation for this? did you do this for ONAP?

**Comment by adrianhopebailie** [comment]
Being addressed as part #95
