### ISSUE TITLE
jackson-datatypes tests not being run by maven/CI

### ISSUE THREAD

**Issue by sublimator** [hyperledger/quilt#156]
No tests in the output: https://circleci.com/gh/hyperledger/quilt/166

I don't really have much experience with mvn but it seems a `<packaging>pom</packaging>` element seems to throw it: https://github.com/hyperledger/quilt/blob/master/jackson-datatypes/pom.xml#L11

No idea why

**Comment by sappenin** [comment]
Nice catch, and correct diagnosis. I included a fix in PR #160 that fixes this issue.
