### ISSUE TITLE
[ilp-core] Add unit test coverage to CodecContext

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#16]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Tuesday May 23, 2017 at 17:12 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/48_

----

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/controlsurface"><img src="https://avatars1.githubusercontent.com/u/32676654?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [controlsurface](https://github.com/controlsurface)**
_Wednesday Oct 18, 2017 at 02:51 GMT_

----

@sappenin Starting to work on this one.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Sunday Oct 22, 2017 at 21:59 GMT_

----

@controlsurface can this be closed? Your tests looked pretty comprehensive but want to be sure you’re not planning to add more.

**Comment by chrisvoicebase** [comment]
@sappenin Yes, can close.  No additional work planned on this one.
