### ISSUE TITLE
Change number-type-mapping for AsnUint8Codec and AsnUint16Codec

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#166]
In order to (de)serialize the [CCP](https://github.com/interledgerjs/ilp-protocol-ccp) to/from ASN.1 OER, it is necessary for the Java codecs to support Uint16 datatypes (in order to (d)encode the identifier of a `route-property`).

This ticket proposes to do this by modifying the underlying Java data-type of `AsnUint8Codec` and `AsnUint16Codec` to be `Short` and `Integer` respectively.

In this way, if we want to write Java code (using the current codec framework) that emits an 8-bit number (in a single octet), we would use a `Short`. If we wanted to write Java code that emits a 16-bit number (2 octets), we would use an `Integer`, and so on. The following illustrates the new proposed mapping of ASN.1 OER datatypes to Java number types:

*  8-bit **Fixed** Length Number (1 octet) --> `Short` [**_changed_**]
* 16-bit **Fixed** Length Number (2 octets) --> `Integer` [**_changed_**]
* 32-bit **Fixed** Length Number (4 octet) --> `Long` [_unchanged_]
* 64-bit **Fixed** Length Number (8 octet) --> `BigInteger` (if X <= `2^64-1`) [_unchanged_]
* Var Octets Number --> `BigInteger` (if X > `2^64-1`) [_unchanged_]

**Comment by sappenin** [comment]
@adrianhopebailie Any thoughts on this one?

**Comment by adrianhopebailie** [comment]
Makes sense. In considering your comments from #164 I wondered if we should have default mappings to native types at all?

Maybe we should encourage any project that uses the framework to create their own context and therefor their own codec -> type mappings?

**Comment by sappenin** [comment]
> Maybe we should encourage any project that uses the framework to create their own context and therefor their own codec -> type mappings

This is an interesting concept. I think we should probably keep a default mapping, but perhaps add better documentation around customization? I'm thinking that the change proposed by this ticket will allow us to support all use-cases, although we'll know more once I finish the CCP codecs.
