### ISSUE TITLE
[ilp-core] Improve README to explain/link-to concepts like "Condition" and "Fulfillment", etc.

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#17]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Wednesday Jul 26, 2017 at 13:45 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/61_

----

Much of the language in our README and Javadoc assumes people know what "Conditions" and "Fulfillments" are and other jargon are. We should not make this assumption, and always provides links or small explanations of various concepts.

One helpful source of truth is the [glossary](https://github.com/interledger/rfcs/blob/master/0019-glossary/0019-glossary.md).

Also, see [this comment](https://github.com/interledger/java-ilp-core/pull/58#discussion_r129572488) here for another example.

**Comment by nathanawmk** [comment]
hi @hyperledger-quilt @sappenin 

I'm interested in working on this issue. I'll start working on this today and will put a WIP PR.

Thank You.

Regards,

Nathan Aw

**Comment by sappenin** [comment]
This is no longer a valid issue. ILP-Core uses only a Preimage condition, which is fairly well documented in the ILP documentation. Crypto-Conditions README's and code have been updated to point to the spec.
