### ISSUE TITLE
element Id is not allow here?

### ISSUE THREAD

**Issue by gccrpm** [hyperledger/quilt#176]
![err](https://user-images.githubusercontent.com/25718696/46245592-af132600-c422-11e8-84c0-904e820fbb4a.png)

i download the project ,opened it using intellij idea ,which occurs an error as in the picture. what's rong with the pom.xml file.

**Comment by sappenin** [comment]
Looks like a typo - it should be `<serverId>`, although this plugin is _only_ used for deploying artifacts, which is only something the project admins can do, so this shouldn't affect anything for you other than be sightly annoying.

I will fix this with my next PR.

**Comment by gccrpm** [comment]
thank you !!! @sappenin  , turned it into <serverId>  works  well。
