### ISSUE TITLE
[ilp-core] Replicate JS Test Vectors for binary encodings

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#19]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Wednesday Jul 26, 2017 at 17:06 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/63_

----

See https://github.com/interledgerjs/ilp-packet/tree/master/test/data

**Comment by adrianhopebailie** [comment]
Closed in favour #142
