### ISSUE TITLE
Publish Quilt JavaDocs

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#2]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Tuesday May 23, 2017 at 07:49 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/48_

----

Need to add build script that publishes JavaDoc to /docs folder

**Comment by sappenin** [comment]
@adrianhopebailie Is this something we still want to do, now that we're in Hyperledger?

**Comment by adrianhopebailie** [comment]
Good question. I think we do still want to produce Javadocs and publish somewhere... WDYT?

**Comment by sappenin** [comment]
I agree that we should publish this somewhere. 

I like what the JavaMoney devs did - they put their [Javadoc on Github](https://javamoney.github.io/apidocs/javax/money/CurrencyUnit.html). If we did the same, we could just link to it from interledger.org. 

However, if you prefer to put all of the Javadoc on interledger.org directlry, I would be fine with that too. Probably whatever is easiest from an automation standpoint...?

**Comment by adrianhopebailie** [comment]
Everything on intertledger.org is hosted on Github pages so I think those are the same thing

**Comment by sudheesh001** [comment]
Just catching up on this thread since it seems to be stale for a while. The docs can be generated by running
```bash
mvn javadoc:aggregate
```
which places the documentation generated into `target/site/apidocs/` which could be hosted on the `gh-pages` branch of this repository after each successful CI build. I'd be happy to help.

**Comment by sappenin** [comment]
For this issue, we should use https://www.javadoc.io/

**Comment by sudheesh001** [comment]
@sappenin Ah I see. So I dug into this a little and realized that the way to do this would be to package `quilt` and publish it along with the sources to a repository like maven central for which we need to create a ticket with Sonatype for `org.interledger` to publish `quilt` as an artifact which needs to be signed with a gpg key. Is there a key for interledger or should this be the developers/maintainers ? 😄Once this is done `javadoc.io` can automatically read the documentation given the groupId and artifact.

**Comment by sappenin** [comment]
>  Is there a key for interledger or should this be the developers/maintainers ?

Hi @sudheesh001. Sonatype publishing is already setup (see [here](https://oss.sonatype.org/content/repositories/snapshots/org/interledger/ilp-core/)), but we haven't had any formal releases yet. 

It would be interesting to see if javadoc.io can use SNAPSHOTS. If not, then once we get all of the tasks in the [v1.0](https://github.com/hyperledger/quilt/labels/v1.0) release finished, then we can release and unblock this ticket.

**Comment by sappenin** [comment]
This is complete. See the README at https://github.com/hyperledger/quilt for links.
