### ISSUE TITLE
[ilp-core] Replicate JS Test vectors for PSK encodings

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#20]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Wednesday Jul 26, 2017 at 17:07 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/64_

----

**Comment by adrianhopebailie** [comment]
Closed in favour #142
