### ISSUE TITLE
Align all codec registration methods

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#200]
We should adjust the manner in which ILP Codecs are registered, for consistency, as follows:

- [ ] In `InterledgerCodecContextFactory` add `.register(CodecContext)` and make it `public`.
- [ ] In `BtpCodecContextFactory`, make the `.register(CodecContext)` method `public`.

Finally,  we should also update the contract for `CodecContextFactory` to mirror the above changes. To make that happen, we should attempt the following (I think this will work, but feel free to report back if this causes too many problems):

* Remove the `CodecContextFactory#OCTET_ENCODING_RULES` constant.
* Remove `public static CodecContext getContext(String encodingRules)` and replace it with a `.oer()` and a `.register(CodecContext)` method like the above factories.

Note this means you'll want to maintain the contents of  `CodecContextFactory#getContext(String encodingRules)` but adjust it to work _without_ the String input. E.g., Instead of throwing an exception, this method should only return OER (i.e., remove the if/else on line 75 of `CodecContextFactory`).

Once that is done, you'll want to start using `CodecContextFactory.oer()` in all of the above factories (`InterledgerCodecContextFactory`, `IldcpCodecContextFactory`, and `BtpCodecContextFactory`).

**Comment by sudheesh001** [comment]
@sappenin Curious about this issue. The `BtpCodecs` are still using an `oer()` method from which the corresponding Error, Message, Packet, Response etc.., are being registered. I basically refactored the `ilp-codecs` to use `register()`. Is this what you meant or am I missing something in this issue?

**Comment by sappenin** [comment]
Hey @sudheesh001 thanks for working on this issue. I think the thrust of this ticket is that each `XYZ...CodecContextFactory` should have two public, static methods available: `.oer()` and `.register(CodecContext)`. I've updated the ticket description with details (See above).

**Comment by sudheesh001** [comment]
Thanks for the clarification @sappenin. I made the changes to the best of my understanding and pushed it at #209. Could you please review it?

In this issue you mention that for the `getContext()` we want to make this work without the string parameter and return an OER encoding. Are there no plans to have other encodings?

In some of the comments on the PR you mentioned that the way to use this would be
`getContext(CodecContextFactory.oer())` but in the updated issue comment you mention `CodecContextFactory.oer()` to be used in other factories. I made the changes for `getContext()` to return only the OER encoding and this is called from `.oer()`. On obtaining the context, we go ahead and register codecs.

Is my understanding correct here or would you need changes to be done? 😄

**Comment by sappenin** [comment]
> Are there no plans to have other encodings?

Not presently. This library is pretty focused on ILPv4, which at this point only uses OER encoding in the actual packet flow.

You've seen the `jackson-datatypes` module which might see to contradict this idea, but in actuality that Jackson module is meant to be used in systems that maybe want to marshall/unmarshal ILP objects in JSON (e.g., a RESTful JSON+HTTP API). 

That context is quite different, however, from the ILPv4 packet flow (outlined [here](https://github.com/interledger/rfcs/blob/master/0027-interledger-protocol-4/0027-interledger-protocol-4.md)) which requires OER.

**Comment by sappenin** [comment]
>  made the changes for getContext() to return only the OER encoding and this is called from .oer(). On obtaining the context, we go ahead and register codecs.

I think that's the right idea, and your PR changes look good overall. I've only made only one counter-suggestion for `CodecContextFactory` itself which doesn't quite fit this pattern (and a few style nits).
