### ISSUE TITLE
Consider a `codecs` sub-module that holds all codecs.

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#204]

**Comment by sappenin** [comment]
This will make the initial interaction with the project a bit easier to grok.

**Comment by sudheesh001** [comment]
Does this mean that the `codecs` module will have additional sub-modules within for `ilp`, `btp` and `ildcp`? as `codecs.ilp`, `codecs.btp` and `codecs.ildcp`?

**Comment by sudheesh001** [comment]
@sappenin Thoughts on this?

**Comment by sappenin** [comment]
> Does this mean that the codecs module will have additional sub-modules within for ilp, btp and ildcp? as codecs.ilp, codecs.btp and codecs.ildcp?

Yes, although I expect the maven module naming convention will be something like ‘codecs-btp’, ‘codecs-ilp’, etc. I think it makes sense to keep these as independent modules so we can publish individual jars for them in case someone wants to only include one particular codec maybe...
