### ISSUE TITLE
[ilp-core] Add Final Zero byte to all Extensible ILP Packets

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#21]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Wednesday Jul 26, 2017 at 17:09 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/65_

----

This is related to #63.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Monday Oct 23, 2017 at 15:19 GMT_

----

Also, see this diagram of the ILP packet for more info: https://interledger.org/rfcs/0003-interledger-protocol/draft-4.html#ilp-payment-packet-format

**Comment by sappenin** [comment]
See https://github.com/interledger/rfcs/issues/352 for more considerations.

**Comment by adrianhopebailie** [comment]
ILPv4 packet no-longer has extensibility byte
