### ISSUE TITLE
Consider making InterledgerAddress.getPrefix non-optional.

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#212]
Give the `SEGMENTS_UNDERFLOW` logic in the InterledgerAddress preconditions checking, we can likely remove the "optionality" of #getPrefix because there will always be a prefix.

Thus, it's likely that the method contract can instead be this:

```java
default InterledgerAddressPrefix getPrefix() {
    ...
```

**Comment by sudheesh001** [comment]
I'll be happy to follow this up once #211 lands 😄
