### ISSUE TITLE
Add test coverage for `InterledgerAddress#of` and `InterledgerAddressPrefix#of`

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#214]
Assuming this coverage doesn't already exist, on both of these classes, we need something like this: 

```java
 @Test(expected = NullPointerException.class)
  public void testOfWithNull() {
    InterledgerAddressPrefix.of(null);
    fail("should have thrown an exception but did not!");
  }

  @Test(expected = IllegalArgumentException.class)
  public void testOfWithEmptyString() {
    try {
      InterledgerAddressPrefix.of("");
      fail("should have thrown an exception but did not!");
    } catch (IllegalArgumentException e) {
      assertThat(e.getMessage(), is("The '' AllocationScheme is invalid!"));
      throw e;
    }
  }

  @Test(expected = IllegalArgumentException.class)
  public void testOfWithBlankString() {
    try {
      InterledgerAddressPrefix.of(" ");
      fail("should have thrown an exception but did not!");
    } catch (IllegalArgumentException e) {
      assertThat(e.getMessage(), is("The ' ' AllocationScheme is invalid!"));
      throw e;
    }
  }
```

**Comment by sudheesh001** [comment]
Looking into this a little it made me realize that implementing the following tests for `InterledgerAddress` and `InterledgerAddressPrefix` do not increase the overall test coverage.
- `testOfWithNull()`,
- `testOfWithEmptyString()` and
- `testOfWithBlankString()`

For the `InterledgerAddress` the missing lines that still need coverage is in `getFirstInvalidityCause()` 

```java
// fault: should have found an error cause
throw new IllegalArgumentException(String.format(
    "Unable to find error for invalid InterledgerAddress: %s", invalidAddressString
));
```

and for `InterledgerAddressPrefix` the missing lines that need coverage are:

```java
return Error.SEGMENTS_UNDERFLOW.getMessageFormat();
```

and 

```java
// fault: should have found an error cause
throw new IllegalArgumentException(String.format(
    "Unable to find error for invalid InterledgerAddress: %s", invalidAddressString
));
```

However, trying to test for the `SEGMENTS_UNDERFLOW` in `InterledgerAddressPrefix`, I am unable to trigger this condition. Is there something I am missing here?
```java
  @Test
  public void test_address_prefix_without_enough_segments() {
    try {
      InterledgerAddressPrefix.of("g");
      fail("Should have failed and been caught as an exception");
    } catch (final IllegalArgumentException e) {
      assertThat(e.getMessage(), is(SEGMENTS_UNDERFLOW.getMessageFormat()));
      throw e;
    }
  }
```

**Comment by sappenin** [comment]
Does that unit test `test_address_prefix_without_enough_segments` pass, or fail in `master`?

**Comment by sudheesh001** [comment]
That's a sample test I've been trying to write to trigger and test the `SEGMENTS_UNDERFLOW` error. It triggers the `fail()` and fails to test the error.

**Comment by sappenin** [comment]
Ah, I see - that makes sense because `g` is a valid `InterledgerAddressPrefix`.

> Looking into this a little it made me realize that implementing the following tests for InterledgerAddress and InterledgerAddressPrefix do not increase the overall test coverage.

I still think we should add overt coverage per my tests above, just in case some future PR changes the oblique coverage and we don't notice.

> For the InterledgerAddress the missing lines that still need coverage is in getFirstInvalidityCause()

This is something that we shouldn't be able to test. It's sort of like, if that ever happens then we have a bug. It's sort of like a Precondition or invariant check, and because the code is currently properly written, there's no way to trigger that condition (which is a good thing, but bad for the coverage dashboard).

> And for InterledgerAddressPrefix the missing lines that need coverage are: `return Error.SEGMENTS_UNDERFLOW.getMessageFormat();`

I don't think this line can ever be reached due to the Regex check. Maybe we can just remove that and use the `SEGMENT_PATTERN` and Regex check to cover this case?

**Comment by sudheesh001** [comment]
> Ah, I see - that makes sense because g is a valid InterledgerAddressPrefix.

Absolutely.

> I still think we should add overt coverage per my tests above, just in case some future PR changes the oblique coverage and we don't notice.

I agree. It's good to have them 😄 

> I wonder if this just means there's a better way to structure this check and we can remove line 294. Need to think a bit more about that.

I'd say instead of removing the final `throw` error in case some corner case slips through the cracks, we could have the error message request the user to report a bug with the test case. We could go ahead and remove the `SEGMENTS_UNDERFLOW` check however since that condition would never be triggered.
