### ISSUE TITLE
Update Javadoc in InterledgerAddressPrefix

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#219]
Much of the javadoc in IntetledgerAddressPrefix errantly says “InterledgetAddress”. This needs to be cleaned up (🧹)

**Comment by sudheesh001** [comment]
So I looked through this and couldn't find the errors where the javadocs say `InterledgetAddress`. I used the IDE's analyze features to find all the typos per module and corrected whichever ones I found. Is there something I am missing in the latest build on master which still has these typo errors? I can't seem to find them doing a github code search on the project either.

**Comment by sappenin** [comment]
Oh, my bad - there was a typo in the issue, which is ironic. 

I meant that the Javadoc for “InterledgerAddressPrefix” sometimes days just “InterledgerAddress.”

E.g., see here:
