### ISSUE TITLE
[ilp-core] Capture Setup Service code in new project

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#23]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Saturday Sep 02, 2017 at 12:41 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/78_

----

Various non-core code was removed in this PR (https://github.com/interledger/java-ilp-core/pull/74/files), so we should probably capture that in a separate project. For example, see the SetupService.

**Comment by adrianhopebailie** [comment]
Stale. The code may be re-used in a future module
