### ISSUE TITLE
[ilp-core] Update README to point to WIKI

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#24]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Saturday Sep 02, 2017 at 13:35 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/79_

----

The wiki now has Usage and Maven coordinates, so we should reduce the size of the README and just point people to the Wiki links.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Sunday Oct 15, 2017 at 17:13 GMT_

----

This is mostly done - just need to update the wiki link to be this link:

https://github.com/interledger/java-ilp-core/wiki/ILP-Core-Home

or possibly just cleanup the wiki. This might change with the move to HL.

**Comment by adrianhopebailie** [comment]
Need to move old wiki content from https://github.com/interledger/java-ilp-core/wiki/ to this repo
