### ISSUE TITLE
Add unit test coverage for all StreamFrameTypes

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#248]
All stream frame types have a derived method called `streamFrameType()` that we need to add unit test coverage for. As part of this ticket, if there is any _other_ derived business logic or otherwise in each StreamFrame we should add coverage for it.

**Comment by theotherian** [comment]
This was resolved in 2e252c2 but I called out the wrong issue

**Comment by sappenin** [comment]
This is complete and merged to `master`.
