### ISSUE TITLE
[ilp-core] Add BTP codecs (using Immutables)

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#25]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Thursday Sep 28, 2017 at 00:45 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/pull/87_

----

Replaces #86 

----

_**[adrianhopebailie](https://github.com/adrianhopebailie)** included the following code: https://github.com/interledger/java-ilp-core/pull/87/commits_

**Comment by sappenin** [comment]
@adrianhopebailie Is this in-scope anymore?

**Comment by adrianhopebailie** [comment]
Fixed in #138
