### ISSUE TITLE
[ilp-core] Switch to using Maven only?

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#26]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Friday Sep 29, 2017 at 18:47 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/88_

----

We currently have an overly complex build system with both Maven and Gradle.

The majority of contributors use Maven and it has proven to be better supported by plugins. It would be helpful to switch but I propose we take a contributor vote.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/earizon"><img src="https://avatars2.githubusercontent.com/u/3679391?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [earizon](https://github.com/earizon)**
_Wednesday Oct 18, 2017 at 11:10 GMT_

----

Not problem for me to default to maven. I vote for the one that simplifies CI. (I'm not aware of the pros and cons of each one for CI)

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Wednesday Oct 18, 2017 at 11:39 GMT_

----

I suggest we implement this change as part of migrating the code over to the Hyperledger Quilt project

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/rizwantanoli"><img src="https://avatars0.githubusercontent.com/u/3721335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rizwantanoli](https://github.com/rizwantanoli)**
_Friday Oct 20, 2017 at 02:37 GMT_

----

I am not a contributor yet, hope to become one, but my preference would be Maven

**Comment by sappenin** [comment]
Maven is now in effect in the quilt project.
