### ISSUE TITLE
Add unit test for F08 packet equation

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#266]
See [discussion here](https://github.com/interledger-rs/interledger-rs/issues/49#issuecomment-473339809) in the Rust connector. The Java implementation uses the correct equation, but we need a small unit test to validate this behavior (this test _may_ already exist, in which case we can just remove the TODO in the Java code and close this issue).

**Comment by theotherian** [comment]
Going to work on the following scenarios:
```
// Scenarios To test
  //
  // data, no max
  // No data, no max

  // no data, max < prepare
  // no data, max == prepare
  // no data, max > prepare

  // data, max < prepare
  // data, max == prepare
  // data, max > prepare
```
