### ISSUE TITLE
[ilp-core] Questions about readme

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#27]
<a href="https://github.com/michielbdejong"><img src="https://avatars2.githubusercontent.com/u/408412?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [michielbdejong](https://github.com/michielbdejong)**
_Tuesday Oct 03, 2017 at 07:47 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/89_

----

What is/are the allowed type(s) for 'hash' in `Condition condition1 = Condition.of(hash)`? 32-bytes, just like for `Fulfillment.of(preimage)`, I guess?

What is/are the allowed type(s) for 'destinationAmount' and for 'data' in `InterledgerPayment.builder().destinationAmount`? And I guess 'address' there has to be an InterledgerAddress object? Or can it also be a String?

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Tuesday Oct 03, 2017 at 15:38 GMT_

----

> What is/are the allowed type(s) for 'destinationAmount' and for 'data' in InterledgerPayment.builder().destinationAmount? 

`destinationAmount` must be a `BigInteger`, and `data` is a `byte[]` (an array of bytes).

> And I guess 'address' there has to be an InterledgerAddress object? Or can it also be a String?

The address is always of type `InterledgerAddress`, which is basically just a wrapper for a String that enforces everything from the RFC, like max-length, and offers some utility functions like, "is this a prefix?" and such.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Wednesday Oct 04, 2017 at 00:30 GMT_

----

> What is/are the allowed type(s) for 'hash' in Condition condition1 = Condition.of(hash)? 32-bytes, just like for Fulfillment.of(preimage), I guess?

`Condition.of(hash)` is validated to be 32 bytes

**Comment by sappenin** [comment]
Closing this as answered - plz reopen if you have further questions.
