### ISSUE TITLE
[ilp-core] Align ILP Error with rfcs/204

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#28]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Saturday Oct 07, 2017 at 18:21 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/91_

----

See https://github.com/interledger/rfcs/pull/204

**Comment by adrianhopebailie** [comment]
No longer required for ILPv4
