### ISSUE TITLE
[ilp-core] Update ILQP per rfc/272

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#29]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Saturday Oct 07, 2017 at 21:55 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/92_

----

See changes in https://github.com/interledger/rfcs/pull/272

**Comment by sappenin** [comment]
ILQP is no longer part of ILP-Core.
