### ISSUE TITLE
StreamSender: Add a Preconditons to ensure money is never lost

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#293]
* Add preconditon to assert that `amountLeftToSend` is NEVER < 0, and "throw" if this ever happens (this means we lost money because we sent more than was delivered).
* Add precondition to assert that `amountDelivered` is NEVER greater-than the `amountToSend` passed into `StreamSender.sendMoney()`, and "throw" if this ever happens (this means we delivered more than we should have)

**Comment by theotherian** [comment]
The first bullet point
> Add preconditon to assert that amountLeftToSend is NEVER < 0, and "throw" if this ever happens (this means we lost money because we sent more than was delivered).
is not actually possible due to the use of UnsignedLong

**Comment by sappenin** [comment]
I think you said that the ‘minus’ operation rolls over past zero, so we should probably have a check for this case, yeah?

**Comment by sappenin** [comment]
Fixed via https://github.com/hyperledger/quilt/pull/334
