### ISSUE TITLE
Allow SharedSecret to accept Base64 and Base64Url encoded bytes?

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#295]
Currently, `SharedSerete#key` returns the bytes of a SharedSecret. Per the RFC, these bytes can be either B64 or B64Url encoded, and [#key supports both encodings](https://github.com/hyperledger/quilt/blob/master/spsp-parent/spsp-core/src/main/java/org/interledger/spsp/SharedSecret.java#L44).

We should determine if [SharedSecret#of](https://github.com/hyperledger/quilt/blob/master/spsp-parent/spsp-core/src/main/java/org/interledger/spsp/SharedSecret.java#L25) should also support both encodings.

**Comment by nhartner** [comment]
It already does accept base64 or base64url text.

**Comment by sappenin** [comment]
My bad - I missed that...
