### ISSUE TITLE
[crypto-conditions] Update test vectors per the RFC README

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#3]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Friday Jul 14, 2017 at 15:41 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/55_

----

The cryptocondition spec's README has some test vectors for library validation. There is a PR (rfcs/crypto-conditions/pull/14) that adds some additional vectors. We should ensure that the java library has full support for all test vectors.

**Comment by sappenin** [comment]
Before implementing this fix, we should instead prefer completing #101, which will probably negate this as an issue.

**Comment by sappenin** [comment]
Closing this in-favor of https://github.com/ripple/crypto-conditions/issues/11
