### ISSUE TITLE
[ilp-core] Fix Javadoc warnings

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#30]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Sunday Oct 15, 2017 at 17:15 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/96_

----

There are > 70 javadoc warnings that should be cleaned up.

**Comment by chrisvoicebase** [comment]
@sappenin  This one can also be closed.
