### ISSUE TITLE
Possible BtpError serialization toString bug?

### ISSUE THREAD

**Issue by sudheesh001** [hyperledger/quilt#313]
I wanted to serialize the `BtpError` message to a `String`, so using the `toString()` method for the following `BtpError` object

```java
private static final byte[] ERROR_DATA = new byte[] {0, 1, 2};

private final BtpError error = BtpError.builder()
      .requestId(REQUEST_ID)
      .errorCode(BtpErrorCode.F00_NotAcceptedError)
      .errorData(ERROR_DATA)
      .triggeredAt(TRIGGERED_AT)
      .subProtocols(SUB_PROTOCOLS)
      .build();
```

I expect the following serialized string on calling `error.toString()`
```
BtpError{ requestId=1, triggeredAt=2019-10-01T17:44:06.459853Z, errorData=[0,1,2], subProtocols=[BtpSubProtocol{contentType=MIME_TEXT_PLAIN_UTF8, protocolName=TEST, data=VGVzdCBEYXRh}], errorCode=F00_NotAcceptedError}
```

but instead I get
```
, subProtocols=[BtpSubProtocol{contentType=MIME_TEXT_PLAIN_UTF8, protocolName=TEST, data=VGVzdCBEYXRh}], errorCode=F00_NotAcceptedError}
```

which is because of this condition in the `toString()` method

```java
 + ", errorData=" + getErrorData() == null ? null : new String(getErrorData())
```

the `getErrorData()` --> `[0,1,2]`. Am I missing something or doing something wrong? Shouldn't we instead be using a safer `byte` to `String` conversion like Base64 / Hex / Oct?

**Comment by theotherian** [comment]
@sudheesh001 it does seem like we should be doing that. From what I can see there's prior art in `BtpSubProtocol`:

```
@Override
    public String toString() {
      return "BtpSubProtocol{"
          + "contentType=" + getContentType()
          + ", protocolName=" + getProtocolName()
          + ", data=" + Base64.getEncoder().encodeToString(getData())
          + "}";
    }
```

Printing raw bytes like that seems fairly useless in a `toString` method, so I think that yes, it's a bug.
