### ISSUE TITLE
Determine path exchange rate before sending payment packets

### ISSUE THREAD

**Issue by nhartner** [hyperledger/quilt#317]
Interledger.js connector does a path exchange rate probe before sending any payment packets to determine if the rate is going to be acceptable. We don't do this currently in Quilt, we can only watch the rates as packets are fulfilled after payment has been started. This could result in payments being initiated then immediately killed once the rate is determined. Maybe that's ok. 

Note: The JS logic also tries to determine a more exact exchange rate using various larger and larger test packet amounts.

Reference: https://github.com/interledgerjs/ilp-protocol-stream/blob/master/src/connection.ts#L1160

**Comment by sappenin** [comment]
We should consider emitting per-packet rate information from the sender so that a higher-level system can aggregate this data into a smart rate service.

**Comment by theotherian** [comment]
We want an external mechanism to do probing and then that will inform the payment tracker.

Also there's an epic discussion here about the issue: https://github.com/interledgerjs/ilp-protocol-stream/issues/112

**Comment by sappenin** [comment]
Probing is working in ILP Pay, which will be merged to master shortly. Closing this issue since StreamSender is now deprecated.
