### ISSUE TITLE
Ignore ConnectionAssetDetails after the first one in a Connection.

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#326]
The Stream RFC is being clarified to indicate that only a single pair of ConnectionAssetDetails should be used per Connection. Thus, we should ensure that the StreamSender ignores subsequent frames of this type if they are sent more than once. 

If the `sendMoney` is called with an overt Denomination, then all such frames should be ignored, with a WARN to indicate if there's a divergence.

**Comment by theotherian** [comment]
We never actually look at this frame beyond the `preflightCheck` in the sender.
