### ISSUE TITLE
Update SimpleSenderIT and SendMoneyExample to use latest interledger-rs docker image

### ISSUE THREAD

**Issue by nhartner** [hyperledger/quilt#328]
We are using an older version of the interledger-rs node docker image. The new image on testnet has API changes that are backwards incompatible. We should update to the latest docker image.

**Comment by sappenin** [comment]
This is blocked by https://github.com/interledger-rs/interledger-rs/issues/333

**Comment by sappenin** [comment]
@nhartner Did this get worked out, or do we still need to coordinate with @dora-gt in https://github.com/interledger-rs/interledger-rs/issues/333?
