### ISSUE TITLE
Start using Stream test fixture from ILP RFC Repo instead

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#368]
[StreamPacketFixtureTest.java](https://github.com/hyperledger/quilt/blob/master/codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/StreamPacketFixturesTest.java) currently uses a fixture in this repo (see [here](https://github.com/hyperledger/quilt/blob/master/codecs-parent/codecs-stream/src/test/resources/StreamPacketFixtures.json)). However, we should instead be using the standard fixture, which is published in the ILP RFC repo [here](https://github.com/interledger/rfcs/tree/master/0029-stream/test-vectors).

**Comment by sudheesh001** [comment]
@sappenin I am not sure if I am missing something here, the fixture in the repo is exactly the same as the one in the ILP RFC repo you've provided. Was there a different intention with this issue?

**Comment by sappenin** [comment]
The concern here is that we want the build to pass on a computer that is not connected to the Internet. Let's keep the local variant of this file, but build something into they CI system that runs nightly to check if the RFC file has changed from our version.

* This is superior to git submodules because those can be difficult to initialize and keep sync'd.
