### ISSUE TITLE
Update Checkstyle Settings

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#369]
This project has [a pom with a checkstyle configuration ](https://github.com/ripple/crypto-conditions/blob/master/pom.xml)that is very similar to Quilt's, and is likely superior. We should experiment with these settings and see if we uncover any checkstyle errors or warnings that we might have missed.

**Comment by sudheesh001** [comment]
On looking through the checkstyle configuration file `checkstyle.xml` in both the projects, it looks like they're the same. Is there something specific we're investigating here?

**Comment by sappenin** [comment]
See https://github.com/ripple/crypto-conditions/pull/32 for the changes that were made in the crypto-conditions project (specifically the regex's for excludes).
