### ISSUE TITLE
Build is broken due to Rust Connector changes

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#407]
Something changed in the `latest` docker image of the Rust connector such that our CI build is no longer passing.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: duplicate field `database_url`', src/libcore/result.rs:1165:5
```
See build logs [here](https://circleci.com/gh/hyperledger/quilt/1435).

We need to update the config for the Rust connector in our ITs in order to fix this.

NOTE: See https://github.com/interledger-rs/interledger-rs/issues/427 for more context here. The Rust team will likely generate a new dockerhub tag, but for now we can use `latest` and keep fixing the build until they give us a stable docker image.

**Comment by sappenin** [comment]
@nkramer44 If you get time, feel free to take a look at this one. @nhartner can assist if it's not immediately clear what the problem is.

**Comment by nkramer44** [comment]
@nhartner did you already take care of this?
https://github.com/interledger-rs/interledger-rs/issues/427#issuecomment-569119129

**Comment by nhartner** [comment]
@nkramer44 I have it fixed on a branch I have in flight

**Comment by nkramer44** [comment]
@sappenin This fix will go with the PR for @nhartner's branch, unless it's blocking anything

**Comment by sappenin** [comment]
This is now fixed.
