### ISSUE TITLE
Possible memory leak in SimpleStreamSender

### ISSUE THREAD

**Issue by nhartner** [hyperledger/quilt#413]
Currently SimpleStreamSender has an overloaded constructor that takes only an IlpOverHttpLink. This then creates an ExecutorService to handle any ILP packet sends. However, once the client is done using SimpleStreamSender it will be garbage collected but the ExecutorService it created will never be shutdown or garbage collected.

Possible solutions:
A. Add a shutdown method to SimpleStreamSender that calls the shutdown method on the executor service. Clients will be responsible to call SimpleStreamSender#shutdown to avoid memory leak.
or 
B. Remove the overloaded constructor that creates an ExecutorService and require the client to always provide one. Clients will be responsible to create and shutdown the ExecutorService they provide to SimpleStreamSender.

**Comment by sappenin** [comment]
StreamSender has been deprecated in-favor of [ILP Pay](https://github.com/hyperledger/quilt/tree/df/ilp-pay) functionality. Closing this.
