### ISSUE TITLE
STREAM Sender: Increment amount sent even in error conditions.

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#425]
The STREAM sender, upon receiving any valid fulfillment, MUST assume that at least the minimum destination amount was delivered.

This normally happens in the happy-path, but if the sender can't decrypt the STREAM packet or some other error happens (e.g., see #424) then the sender MUST be sure to still increment the total amount received in its tracker.

Otherwise, this might lead to a vulnerability.

See discussion in Slack here: https://interledger.slack.com/archives/CPPG86V40/p1580420906004000

**Comment by kincaidoneil** [comment]
Here's one case that needs to be fixed. If the recipient lied in the STREAM packet to say they sent a reject when the packet was actually fulfilled, the delivered amount won't be credited to the payment tracker:

https://github.com/hyperledger/quilt/blob/9a943236c12a0a1b670564f164ba60e8f9ce3f4e/stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java#L747-L755

**Comment by sappenin** [comment]
See https://github.com/interledger-rs/interledger-rs/pull/635 for more details

**Comment by sappenin** [comment]
StreamSender has been deprecated in-favor of [ILP Pay](https://github.com/hyperledger/quilt/tree/df/ilp-pay) functionality. Closing this.
