### ISSUE TITLE
SimpleStreamSender should compute prepare packet expiresAt just before sending

### ISSUE THREAD

**Issue by nhartner** [hyperledger/quilt#432]
Currently SimpleStreamSender is submitting prepare packets to its `ExecutorService` to be sent but computing the expiresAt before submitting. In situations where the executorService is overwhelmed with packets to send, calling `executorService.submit()` can cause a packet to be queued up and not immediately sent. If the packet is queued for more than 30s (which I have seen happen under load), then prepare packet expiresAt is already expired. A better approach would be to construct the prepare packet just before sending occurs (i.e. after the packet has been queued and is now being executed).

**Comment by sappenin** [comment]
@nhartner Can we close this issue?
