### ISSUE TITLE
[crypto-conditions] Use the term "Validate" instead of "Verify"?

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#44]
Per https://github.com/rfcs/crypto-conditions/issues/28, the question of whether to use the term `verify` vs `validate` was raised. The [spec](https://tools.ietf.org/html/draft-thomas-crypto-conditions-03) and the JS implementation use the term `validate` when referring to the evaluation of a fulfillment.

What does everyone think about changing the name of `Fulfillment#verify` to be `Fulfillment#validate` to align with the spec and the JS implementation.

I realize that, at first glance, this might take us away from the goal of being able to treat crypto-conditions as generic JCA code (best example is `java.security.Signature#verify`), but considering our previous discussions, perhaps it might be a good idea to use a different term like `Validate` so we don't confuse the difference between Signature verification and a CryptoCondition validation/verification?

Additionally, would we be better off designing some sort of wrapper interface for crypto-conditions to allow them to more pluggably be used in Java/JCA systems?

(I'm not entirely sure about this proposal, so feel free to push back with alternative ideas).

**Comment by adrianhopebailie** [comment]
I think the other implementations are wrong. The correct term is verify IMO.

@justmoon WDYT?

**Comment by justmoon** [comment]
The spec uses the term "validate". I think either term is fine, don't feel strongly about it. But it should be consistent, so if you want to use verify, you should make a PR against the spec.

**Comment by sappenin** [comment]
@adrianhopebailie still want to use `verify`? If so, I'll make a PR for the CC spec.

I don't have a strong opinion about which word to use, but agree that we should be consistent.

**Comment by sappenin** [comment]
Closing in-favor of https://github.com/ripple/crypto-conditions/issues/4
