### ISSUE TITLE
Unable to run the sample Example

### ISSUE THREAD

**Issue by ashlinSajan** [hyperledger/quilt#471]
Hi @sappenin  and @ryjones ,

I am trying to run the payment example in the repository.Have installed maven and gradle.But confused how to run.Could you please provide some commands on how to run the sample example given.

**Comment by sappenin** [comment]
Hi @ashlinSajan -- can you clarify which example you're trying to run? There's [this guide](https://github.com/hyperledger/quilt/tree/master/examples-parent/send-money) that should help you, but is that one not working? 

(it's possible the docs are a bit out of date).

**Comment by ashlinSajan** [comment]
> Hi @ashlinSajan -- can you clarify which example you're trying to run? There's [this guide](https://github.com/hyperledger/quilt/tree/master/examples-parent/send-money) that should help you, but is that one not working?
> 
> (it's possible the docs are a bit out of date).

Hi @sappenin,
I have gone through the same example,but didn't find any commands to run the code.Could you provide the necessary command.This example README docs didn't specify any commands

**Comment by sappenin** [comment]
Hi @ashlinSajan,

Sure thing - you'll want to open the project in an IDE, and then locate this file ([SendMoneyExample.java](https://github.com/hyperledger/quilt/blob/master/examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java)). You should be able to run this in your IDE.

If you're not familiar with that, drop me a line here and I can try to dig up a command-line command for you.

**Comment by ashlinSajan** [comment]
Hi David,

I am not familiar how to run in the IDE.Could you please send the CLI Command if possible that would be helpful.

Thanks and Regards,

Ashlin
________________________________

**Comment by sappenin** [comment]
Hi @ashlinSajan - apologies for the delay here, but circling back to this. 

This example is best run from an IDE while stepping through it with the debugger so you can become familiar with what the Stream SendMoney code is doing. Consider downloading [Intelij IDEA](https://www.jetbrains.com/idea/) and becoming familiar with an IDE. It will really make things more enjoyable if you're planning to develop software in Java.

With that said, you can do the following to run from the command line:

```
/quilt %> cd examples-parent/
/quilt/examples-parent %> cd send-money/ 
/quilt/examples-parent/send-money %> mvn spring-boot:run
```

Note that you'll want to build the project first using Maven. See [this project's README](https://github.com/hyperledger/quilt/blob/master/README.md#build-the-project) for more information.
