### ISSUE TITLE
[crypto-conditions] Test the Java implementation against https://github.com/rfcs/crypto-conditions/issues/30

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#6]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Tuesday Oct 17, 2017 at 18:04 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/72_

----

Test the Java implementation against https://github.com/rfcs/crypto-conditions/issues/30

**Comment by sappenin** [comment]
Closing in-favor of https://github.com/ripple/crypto-conditions/issues/9
