### ISSUE TITLE
Create a CONTRIBUTING file

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/quilt#61]
I could not locate a CONTRIBUTING file in the latest Hyperledger Quilt code. Please add a CONTRIBUTING file that contains information on how to contribute to the development of Hyperledger Quilt.

**Comment by adrianhopebailie** [comment]
Should include some explanation of the project structure and modules and how they work together

**Comment by adrianhopebailie** [comment]
Include standards such as README for each module

**Comment by adrianhopebailie** [comment]
Include link to @earizon 's map: https://earizon.github.io/IT_notes/Interledger/interledger_map.html
