### ISSUE TITLE
ThresholdSha256Condition#calculateCost doesn't accept an Immutable list

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#67]
`ThresholdSha256Condition#calculateCost` performs a sort operation on the list, which fails if the supplied List is immutable. We should copy the list into a mutable variant before trying to sort it.

**Comment by nathanawmk** [comment]
hi @sappenin 

I'm interested in working on this issue. I'll start working on this today and will put a WIP PR.

Thank You.

Regards,

Nathan Aw

**Comment by reedrosenbluth** [comment]
https://github.com/hyperledger/quilt/pull/122

**Comment by sappenin** [comment]
This is now fixed.
