### ISSUE TITLE
[crypto-conditions] Fix Condition Constructor modifiers

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#7]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Thursday Oct 19, 2017 at 18:23 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/74_

----

See [this comment](https://github.com/interledger/java-crypto-conditions/pull/73/files#r145783281) for more details, but we should inspect the Constructor of each Condition and make sure it's modifier is correct. For example, in `PreimageSha256` in the PR linked above, the public constructor should be package-private, and the package-private constructor should be public.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Friday Oct 20, 2017 at 09:33 GMT_

----

Fixed for PreimageSha256 in #73

**Comment by sappenin** [comment]
This is no longer applicable as of 0.5.0-SNAPSHOT. All conditions/fulfillments are now interfaces, with immutables-generated implementations.
