### ISSUE TITLE
`ThresholdSha256Condition#calculateCost` doesn't check that the number of its sub-conditions is greater or equal to its threshold

### ISSUE THREAD

**Issue by pascalav** [hyperledger/quilt#71]
In draft-03 is told: 

> in the case of the THRESHOLD-SHA-256 type the number of valid sub-fulfillments must be equal or greater than the threshold

In sources, providing less sub-conditions than the provided threshold throws an `IndexOutOfBoundsException`.

Semantically, throwing an `IllegalArgumentException` would better describe the situation.

**Comment by pascalav** [comment]
A pull request is available: https://github.com/hyperledger/quilt/pull/72

Unit test was added sideways (see https://github.com/hyperledger/quilt/issues/10).

**Comment by pascalav** [comment]
I just read `ThresholdSha256Fulfillment.java` and I'm probably wrong opening this issue. I thought "conditions" and "fulfillments" were narrowing to the same piece of data.

**Comment by sappenin** [comment]
Fixed by #81
