### ISSUE TITLE
[crypto-conditions] Consider Removing Condtion.getFingerprintBase64Url

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#9]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Thursday Oct 19, 2017 at 18:39 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/76_

----

See discussion in this PR: https://github.com/interledger/java-ilp-core/pull/102#issuecomment-337885767

The reason `Condtion#getFingerprintBase64Url` was introduced was to try and create a truly immutable implementation of each condition. However, this encoding is a bit ambiguous (e.g., is padding used, or not, etc), and while this ambiguity could be cleared-up in Javadoc, perhaps it's better to simply remove this method entirely, and return a copy of the bytes in any implementation of `Condition#getFingerprint`.

The downside of this is possibly performance, but as @adrianhopebailie  indicated, these are only 32 bytes, and if somebody encounters a perf problem, we could potentially add a new method to just return a reference to the array. The reason we aren't doing that now is mutability -- returning a reference to the array would allow an external caller to mutate the array (though this is likely already possible via Reflection, so until Java introduces an immutable byte array, there's probably not much use in trying to guard against this -- unless we want to _only_ store a String, but that has its own downsides due to potential encoding/decoding mistakes on the part of a developer).

**Comment by sappenin** [comment]
The main rationale for this issue was to align CryptoConditions with JCA. However, closing this for now. since the byte[] method still exists, and we should probably consider just mapping from CC to JCA if that ever becomes a use-case. 

Plz re-open if anyone feels otherwise.
