### ISSUE TITLE
Formalize versioning and release process

### ISSUE THREAD

**Issue by adrianhopebailie** [hyperledger/quilt#95]
@earizon and @sappenin initiated a discussion around this in #90 

Having read through [the blog](https://www.dontpanicblog.co.uk/2011/12/13/maven-release-plugin/) linked in the thread I found the following to be interesting and need our attention:

> The version of all sub-modules should be the same as the version of the parent pom and all sub-modules should be released together.

I suggest we fix this in all our sub-modules but consider pulling some sub-modules out into their own project like crypto-conditions and the codec-framework as these don't make sense as modules that will be re-released with each new version of the Interledger components.

Also, given the changes with ILPv4 we may consider changing `ilp-core` to no longer depend on `crypto-conditions`...

I think part of our problem is that we are in a very experimental stage and are making breaking changes to the APIs regularly. The sooner we get out of that the better then we can follow a better release process.

On the one hand I agree with @earizon that SNAPSHOT releases are supposed to indicate that they are an interim state but I also think that if we change the API from one commit to another then that will break any applications that use the API and so this needs to be signaled by a version number change.

I propose that we say:

1. If you submit a change that breaks any API then the version number must increment
2. If you submit a change that doesn't break an API then it's okay to leave the version number unchanged if the change is being made on a SNAPSHOT.

## Proposal

Let me know what you think of doing each of these:

1. Put crypto-conditions in it's own repo and leave version at `0.5.0-SNAPSHOT`
2. Set versions of all modules and submodules to `1.0.0-SNAPSHOT` with a goal of making a release following our call on 14 February
3. Get the repo setup to use the `maven-release` plugin correctly and aim to make formal releases after our bi-weekly call unless there is an important bug-fix.
4. Setup the CI to make a SNAPSHOT release every time we merge into `master`

**Comment by sappenin** [comment]
Agree with all suggestions - I can work on pulling out crypto-conditions into a new project.

@adrianhopebailie Should that still be in hyperledger? If so, what should we call it?

**Comment by sappenin** [comment]
> Also, given the changes with ILPv4 we may consider changing ilp-core to no longer depend on crypto-conditions...

I would like to break the crypto-conditions project into sub-modules, one of which will be `crypto-conditions-api` that will basically just have interfaces and immutable-implementations (but not codecs, etc).

I propose that we pull that minimal dependency into `ilp-core` so that users of both libraries don't have to worry about having two different variants of something called "crypto-condition".

**Comment by adrianhopebailie** [comment]
> I propose that we pull that minimal dependency into ilp-core so that users of both libraries don't have to worry about having two different variants of something called "crypto-condition".

Yes, I thought about that too. I think that would be a great idea.

> Should that still be in hyperledger?

I actually think it should be in a public repo under @ripple but not sure if that's something we can do. Will find out.

**Comment by adrianhopebailie** [comment]
Crypto-conditions is now at: https://github.com/ripple/crypto-conditions

 - All modules and submodules are now at 0.12.0-SNAPSHOT with a goal of making a 1.0.0-RELEASE when ready.
 - Until then we'll continue to increment minor version regularly
 - @sappenin will manage releases following v1.
 - We'll setup the CI to make a SNAPSHOT release every time we merge into master after v1.
